version: "3.8"

services:
  database:
    image: postgres:12.4-alpine
    environment:
      - POSTGRES_USER=booking
      - POSTGRES_PASSWORD=booking
      - POSTGRES_DB=hotel-booking
    ports:
      - "5432:5432"

  db-gui:
    image: dpage/pgadmin4:6.7
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"

networks:
  default:
    name: local_development_network